spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
#    url: jdbc:postgresql://localhost:5432/TableTime
#    username: postgres
#    password: qaz%123%
#    driver-class-name: org.postgresql.Driver
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    url: jdbc:postgresql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:5432}/${PROD_DB_NAME:TableTime}
#    username: ${PROD_DB_USERNAME:postgres}
#    password: ${PROD_DB_PASSWORD:qaz%123%}
#    driver-class-name: org.postgresql.Driver
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${POSTGRES_DB:TableTime}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:qaz%123%}
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    time: 86400000
