spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
#    url: jdbc:postgresql://localhost:5432/TableTime
#    username: postgres
#    password: qaz%123%
#    driver-class-name: org.postgresql.Driver
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  PROD_DB_HOST=monorail.proxy.rlwy.net
#  PROD_DB_PORT=23179
#  PROD_DB_NAME=railway
#  PROD_DB_USERNAME=postgres
#  PROD_DB_PASSWORD=tIZHnOmjCFnZAYOXeNodNWbgmQJuxHSL

#  PROD_DB_HOST=monorail.proxy.rlwy.net
#  PROD_DB_PORT=44728
#  PROD_DB_NAME=railway
#  PROD_DB_USERNAME=postgres
#  PROD_DB_PASSWORD=YKPmHEUwweShnkvERNLDRBQVuQUfcVvI


token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    time: 86400000
